import! [metadata, rule_hint=c.link] libs = libwuffs%lib{wuffs}

have_cpp = $($libs: libwuffs.cpp)

# C smoke (default package build).
#
./: exe{driver}: include = (!$have_cpp)
[rule_hint=c.link] \
exe{driver}: {h c}{**} $libs

# C++ smoke (config.libwuffs.cpp=true), covers wuffs_aux.
#
./: exe{aux}: include = $have_cpp
exe{aux}: cxx{aux} $libs
